openapi: 3.1.0
info:
  title: Available Market Stock API
  version: 1.0.0
  description: >
    Handles creation, retrieval, and adjustment of Available Market Stock (AMS)
    documents for logistic centers, used by Farmer Managers and backend order processes.
    All operations require authentication. Quantity adjustments now use **farmerOrderId**
    instead of internal subdocument `_id`.

tags:
  - name: AvailableMarketStock
    description: Endpoints to manage and adjust available market stock for shifts. seed:ams

paths:
  /api/available-stock/init:
    post:
      summary: Initialize (or find existing) Available Market Stock document
      description: >
        Creates or retrieves an AvailableMarketStock document for a given logistic center,
        date, and shift. Only Farmer Managers can create.
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [LCid, date, shift]
              properties:
                LCid:
                  type: string
                  description: Logistic center ObjectId
                  example: "66e007000000000000000001"
                date:
                  type: string
                  format: date
                  example: "2025-10-22"
                shift:
                  type: string
                  enum: [morning, afternoon, evening]
                  example: "morning"
      responses:
        "200":
          description: AMS document found or created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailableMarketStock"
        "400":
          description: Missing required parameters
        "500":
          description: Server or database error

  /api/available-stock:
    get:
      summary: Get Available Market Stock document by LC + date + shift
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
        - in: query
          name: date
          required: true
          schema: { type: string, format: date }
        - in: query
          name: shift
          required: true
          schema: { type: string, enum: [morning, afternoon, evening] }
      responses:
        "200":
          description: The requested Available Market Stock document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailableMarketStock"
        "404":
          description: Not found
        "400":
          description: Invalid or missing query params

  /api/available-stock/{docId}:
    get:
      summary: Get Available Market Stock by document ID
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: docId
          required: true
          schema: { type: string }
          description: AMS document ObjectId
      responses:
        "200":
          description: AMS document retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailableMarketStock"
        "404":
          description: Not found or invalid ID

  /api/available-stock/upcoming:
    get:
      summary: List upcoming AMS documents (today onward)
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
        - in: query
          name: count
          schema: { type: integer, default: 5 }
        - in: query
          name: fromDate
          schema: { type: string, format: date }
      responses:
        "200":
          description: List of upcoming AMS documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AvailableMarketStock"

  /api/available-stock/next5:
    get:
      summary: List next five shifts that have stock available
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
          description: Logistic center ID
      responses:
        "200":
          description: Array of upcoming shifts that contain available items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date: { type: string, example: "2025-10-22" }
                    shift: { type: string, example: "morning" }
                    docId: { type: string }
                    deliverySlotLabel: { type: string, example: "08:00–12:00" }

  /api/available-stock/adjustQty:
    post:
      summary: Adjust available quantity by kilograms
      description: >
        Adjust an item’s available stock by **kilograms**, identified by `farmerOrderId`.
        Use negative delta for reservation, positive for release.
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [docId, farmerOrderId, deltaKg]
              properties:
                docId:
                  type: string
                  description: AMS document ObjectId
                farmerOrderId:
                  type: string
                  description: FarmerOrder ObjectId (unique per line)
                deltaKg:
                  type: number
                  description: >
                    Change in available KG (negative = reserve, positive = release)
                  example: -12.5
                enforceEnoughForReserve:
                  type: boolean
                  default: true
                autoSoldoutOnZero:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Stock adjusted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  docId: { type: string }
                  farmerOrderId: { type: string }
                  newQty: { type: number }
                  unitsLeft: { type: number, nullable: true }
                  status: { type: string, enum: [active, soldout, removed], nullable: true }
        "400":
          description: Validation error or missing parameters
        "409":
          description: Not enough available quantity or concurrency issue

  /api/available-stock/adjustQtyUnits:
    post:
      summary: Adjust available quantity by units
      description: >
        Adjusts an item’s available stock by **units**, converting to KG internally.
        Negative = reserve, positive = release.
      tags: [AvailableMarketStock]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [docId, farmerOrderId, unitsDelta]
              properties:
                docId:
                  type: string
                farmerOrderId:
                  type: string
                unitsDelta:
                  type: number
                  example: -10
                enforceEnoughForReserve:
                  type: boolean
                  default: true
                autoSoldoutOnZero:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Units adjusted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  docId: { type: string }
                  farmerOrderId: { type: string }
                  newQty: { type: number }
                  unitsLeft: { type: number, nullable: true }
                  status: { type: string, enum: [active, soldout, removed], nullable: true }
        "400":
          description: Invalid parameters
        "409":
          description: Not enough stock or unit mismatch

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AvailableMarketStock:
      type: object
      properties:
        _id:
          type: string
          description: Document ID
        LCid:
          type: string
          description: Logistic Center ObjectId
        availableDate:
          type: string
          format: date
        availableShift:
          type: string
          enum: [morning, afternoon, evening]
        items:
          type: array
          items:
            type: object
            properties:
              itemId: { type: string }
              displayName: { type: string }
              category: { type: string }
              pricePerKg: { type: number }
              pricePerUnit: { type: number, nullable: true }
              currentAvailableQuantityKg: { type: number }
              originalCommittedQuantityKg: { type: number }
              farmerOrderId: { type: string }
              farmerID: { type: string }
              farmerName: { type: string }
              farmName: { type: string }
              farmLogo: { type: string, nullable: true }
              unitMode: { type: string, enum: [kg, unit, mixed] }
              estimates:
                type: object
                properties:
                  avgWeightPerUnitKg: { type: number }
                  sdKg: { type: number }
                  availableUnitsEstimate: { type: number, nullable: true }
                  unitBundleSize: { type: number }
                  zScore: { type: number }
                  shrinkagePct: { type: number }
              status: { type: string, enum: [active, soldout, removed] }
