openapi: 3.0.3
info:
  title: Available Market Stock API
  version: 1.0.0
  description: |
    API for managing available market stock by Logistic Center (LC), date, and shift.

servers:
  - url: /api/market

tags:
  - name: AvailableStock
    description: Manage available market stock docs and items

paths:
  /market/available-stock/init:
    post:
      tags: [AvailableStock]
      summary: Create or find a stock document for a given LC + date + shift
      description: |
        Creates the `(LCid + date + shift)` document if it does not exist, otherwise returns the existing one.
        **Auth:** Bearer token required. **Role:** `fManager` required.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [LCid, date, shift]
              properties:
                LCid:
                  $ref: '#/components/schemas/ObjectId'
                date:
                  type: string
                  format: date
                  description: Calendar date (YYYY-MM-DD); normalized to 00:00 UTC internally
                shift:
                  $ref: '#/components/schemas/ShiftName'
      responses:
        '200':
          description: Created or existing AvailableMarketStock document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableMarketStock'
        '400':
          description: Missing required fields
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Failed to init available market stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /market/available-stock:
    get:
      tags: [AvailableStock]
      summary: Get a stock doc by LC + date + shift
      description: Returns the document that matches `(LCid, date, shift)`.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { $ref: '#/components/schemas/ObjectId' }
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date
            description: YYYY-MM-DD
        - in: query
          name: shift
          required: true
          schema: { $ref: '#/components/schemas/ShiftName' }
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableMarketStock'
        '400':
          description: Missing params
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '404':
          description: Not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '500':
          description: Failed to fetch
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /market/available-stock/{docId}:
    get:
      tags: [AvailableStock]
      summary: Get a stock doc by its ID
      description: Fetches an `AvailableMarketStock` by `_id`.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: docId
          required: true
          schema: { $ref: '#/components/schemas/ObjectId' }
      responses:
        '200':
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableMarketStock'
        '400':
          description: Missing docId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '404':
          description: Not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /market/available-stock/upcoming:
    get:
      tags: [AvailableStock]
      summary: List upcoming stock docs for an LC
      description: Returns upcoming (today and forward) stock docs for the LC, any shift.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { $ref: '#/components/schemas/ObjectId' }
        - in: query
          name: count
          required: false
          schema:
            type: integer
            minimum: 1
            default: 5
        - in: query
          name: fromDate
          required: false
          schema:
            type: string
            format: date
            description: Start date (YYYY-MM-DD). Defaults to today.
      responses:
        '200':
          description: Array of upcoming docs
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/AvailableMarketStock' }
        '400':
          description: Missing LCid
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '500':
          description: Failed to list
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /market/available-stock/next5:
    get:
      tags: [AvailableStock]
      summary: Next 5 shifts (by LC timezone) that have stock items
      description: |
        Looks at the next 5 upcoming shifts (per LC timezone) and returns those that **have items**.
        Each result includes a delivery time-slot label derived from the shift configuration.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { $ref: '#/components/schemas/ObjectId' }
        - in: query
          name: fromTs
          required: false
          schema:
            type: number
            format: double
            description: Optional Unix timestamp (ms) to start from
      responses:
        '200':
          description: Matching next shifts with stock
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NextFiveShiftItem'
        '400':
          description: Missing LCid
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '500':
          description: Failed to list next five shifts
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /market/available-stock/adjustQty:
    post:
      tags: [AvailableStock]
      summary: Atomically adjust available quantity for a specific line item
      description: |
        Adjusts `items[n].currentAvailableQuantityKg` by `deltaKg` (negative=reserve, positive=release).
        When `enforceEnoughForReserve=true` (default), reserves that exceed the available qty are rejected.
        If `autoSoldoutOnZero=true` (default) and the new qty hits 0, the line status is set to `soldout`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjustQtyRequest'
      responses:
        '200':
          description: Adjustment result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdjustQtyResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '404':
          description: Document or line not found after update
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        '409':
          description: Conflict (e.g., not enough available quantity to reserve)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ObjectId:
      type: string
      description: MongoDB ObjectId
      pattern: '^[a-fA-F0-9]{24}$'
      example: 6512bd43d9caa6e02c990b0a

    ShiftName:
      type: string
      description: Shift name
      enum: [morning, afternoon, evening, night]

    ItemStatus:
      type: string
      enum: [active, soldout, removed]

    AvailableStockItem:
      type: object
      required:
        - itemId
        - displayName
        - category
        - pricePerUnit
        - currentAvailableQuantityKg
        - originalCommittedQuantityKg
        - farmerID
        - farmerName
        - farmName
        - status
      properties:
        _id:
          $ref: '#/components/schemas/ObjectId'
        itemId:
          $ref: '#/components/schemas/ObjectId'
        displayName:
          type: string
          example: Red Gala Apples
        imageUrl:
          type: string
          nullable: true
          example: https://cdn.example.com/items/apples.jpg
        category:
          type: string
          example: fruit
        pricePerUnit:
          type: number
          format: double
          minimum: 0
          example: 7.99
        currentAvailableQuantityKg:
          type: number
          format: double
          minimum: 0
          example: 120
          description: Must be ≤ originalCommittedQuantityKg
        originalCommittedQuantityKg:
          type: number
          format: double
          minimum: 0
          example: 150
        farmerOrderId:
          allOf:
            - $ref: '#/components/schemas/ObjectId'
          nullable: true
        farmerID:
          $ref: '#/components/schemas/ObjectId'
        farmerName:
          type: string
          example: John Doe
        farmName:
          type: string
          example: Sunny Farm
        status:
          $ref: '#/components/schemas/ItemStatus'

    AvailableMarketStock:
      type: object
      description: Root document for a given LC + date + shift
      properties:
        _id:
          $ref: '#/components/schemas/ObjectId'
        availableDate:
          type: string
          format: date-time
          description: Stored normalized to 00:00:00.000Z
          example: 2025-09-18T00:00:00.000Z
        availableShift:
          $ref: '#/components/schemas/ShiftName'
        LCid:
          $ref: '#/components/schemas/ObjectId'
        createdById:
          allOf:
            - $ref: '#/components/schemas/ObjectId'
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/AvailableStockItem'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    NextFiveShiftItem:
      type: object
      properties:
        date:
          type: string
          description: ISO date string (YYYY-MM-DD)
          example: '2025-09-18'
        shift:
          $ref: '#/components/schemas/ShiftName'
        docId:
          $ref: '#/components/schemas/ObjectId'
        deliverySlotLabel:
          type: string
          example: '09:00–11:00'

    AdjustQtyRequest:
      type: object
      required: [docId, lineId, deltaKg]
      properties:
        docId:
          $ref: '#/components/schemas/ObjectId'
        lineId:
          $ref: '#/components/schemas/ObjectId'
        deltaKg:
          type: number
          format: double
          description: Negative=reserve (decrement), Positive=release (increment); must be non-zero
          example: -3.5
        enforceEnoughForReserve:
          type: boolean
          default: true
        autoSoldoutOnZero:
          type: boolean
          default: true

    AdjustQtyResponse:
      type: object
      required: [ok, docId, lineId, newQty]
      properties:
        ok:
          type: boolean
          example: true
        docId:
          $ref: '#/components/schemas/ObjectId'
        lineId:
          $ref: '#/components/schemas/ObjectId'
        newQty:
          type: number
          format: double
          example: 116.5
        status:
          $ref: '#/components/schemas/ItemStatus'
          description: Present when auto-soldout triggered

    Error:
      type: object
      properties:
        error:
          type: string
          example: Not found
