openapi: 3.0.3
info:
  title: Available Market Stock API
  version: 1.0.0

paths:
  /api/market/available-stock/init:
    post:
      summary: Create or find AvailableMarketStock document
      description: Creates or finds an AvailableMarketStock doc for LC + date + shift.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [LCid, date, shift]
              properties:
                LCid:
                  type: string
                  example: LC-1
                date:
                  type: string
                  format: date
                  example: 2025-09-16
                shift:
                  type: string
                  enum: [morning, afternoon, evening, night]
      responses:
        "200":
          description: AvailableMarketStock document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailableMarketStock"

  /api/market/available-stock:
    get:
      summary: Get AvailableMarketStock by LC/date/shift
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
        - in: query
          name: date
          required: true
          schema: { type: string, format: date }
        - in: query
          name: shift
          required: true
          schema: { type: string, enum: [morning, afternoon, evening, night] }
      responses:
        "200":
          description: AvailableMarketStock document
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailableMarketStock"

  /api/market/available-stock/next5:
    get:
      summary: Get next 5 shifts that have stock
      description: Returns the next 5 shifts (based on LC timezone) that already have stock items.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
        - in: query
          name: fromTs
          required: false
          schema: { type: integer, format: int64 }
          description: Optional epoch millis (used for testing)
      responses:
        "200":
          description: List of shifts with stock
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                    shift:
                      type: string
                      enum: [morning, afternoon, evening, night]
                    docId:
                      type: string
                      description: AvailableMarketStock document ID

  /api/market/available-stock/upcoming:
    get:
      summary: List upcoming available stock documents
      description: Returns upcoming AvailableMarketStock docs for the LC, starting today.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: LCid
          required: true
          schema: { type: string }
        - in: query
          name: count
          required: false
          schema: { type: integer, default: 6 }
        - in: query
          name: fromDate
          required: false
          schema: { type: string, format: date }
      responses:
        "200":
          description: List of AvailableMarketStock documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AvailableMarketStock"

  /api/market/available-stock/adjustQty:
    post:
      summary: Adjust available quantity for a stock line
      description: Reserve or release quantity on a specific line item.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [docId, lineId, deltaKg]
              properties:
                docId:
                  type: string
                  description: AvailableMarketStock document ID
                lineId:
                  type: string
                  description: Subdocument line ID (inside items[])
                deltaKg:
                  type: number
                  description: Negative = reserve, Positive = release
                enforceEnoughForReserve:
                  type: boolean
                  default: true
                autoSoldoutOnZero:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Adjustment result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  docId:
                    type: string
                  lineId:
                    type: string
                  newQty:
                    type: number
                  status:
                    type: string
                    enum: [active, soldout, removed]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AvailableMarketStock:
      type: object
      properties:
        _id:
          type: string
        LCid:
          type: string
        availableDate:
          type: string
          format: date
        availableShift:
          type: string
          enum: [morning, afternoon, evening, night]
        createdById:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/AvailableStockItem"

    AvailableStockItem:
      type: object
      properties:
        _id:
          type: string
        itemId:
          type: string
        displayName:
          type: string
        imageUrl:
          type: string
        category:
          type: string
        pricePerUnit:
          type: number
        currentAvailableQuantityKg:
          type: number
        originalCommittedQuantityKg:
          type: number
        farmerOrderId:
          type: string
        farmerID:
          type: string
        farmerName:
          type: string
        farmName:
          type: string
        status:
          type: string
          enum: [active, soldout, removed]
