openapi: 3.0.3
info:
  title: Demand Statics API
  version: "1.0.0"
  description: >
    Endpoints for reading and maintaining demand statics "slots" keyed by `<day>-<part>` (e.g., `monday-afternoon`).
    Notes:
      - Public reads allow optional authentication (JWT bearer); mutations require authentication with one of the roles:
        `tManager`, `fManager`, `opManager`, `admin`.
      - Two body shapes are supported on create/upsert/import:
        1) **Normalized**: `{ slotKey, items: [...] }`
        2) **Raw**: `{ "<slotKey>": { items: [...] } }`
      - Valid day names: `monday`…`sunday`.
      - Valid parts: `morning`, `afternoon`, `night`.

tags:
  - name: DemandStatics
    description: Average demand per slot (day + part)

servers:
  - url: /api

paths:
  /demand-statics:
    get:
      tags: [DemandStatics]
      summary: List demand statics slots
      description: >
        Returns a paginated list of all configured demand statics slots.
        Optional filters: `day`, `part`.
        Public route (optional authentication).
      parameters:
        - in: query
          name: page
          required: false
          schema: { type: integer, minimum: 1, default: 1 }
          description: "Page number (1-based)."
        - in: query
          name: limit
          required: false
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
          description: "Page size (1–100)."
        - in: query
          name: day
          required: false
          schema: { $ref: '#/components/schemas/DayName' }
          description: "Filter by day (e.g., `monday`)."
        - in: query
          name: part
          required: false
          schema: { $ref: '#/components/schemas/PartName' }
          description: "Filter by part (e.g., `afternoon`)."
      responses:
        "200":
          description: Paginated list of demand statics slots
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ListSlotsResponse' }
              examples:
                sample:
                  value:
                    items:
                      - slotKey: "monday-afternoon"
                        items:
                          - { itemId: "68960284330bf1699eee8955", itemDisplayName: "Lettuce Romaine", averageDemandQuantityKg: 42.5 }
                      - slotKey: "monday-night"
                        items: []
                    page: 1
                    limit: 20
                    total: 2
                    pages: 1
        "400":
          description: Invalid query
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

    post:
      tags: [DemandStatics]
      summary: Create a demand statics slot
      description: >
        Creates a new slot document.
        Accepts **normalized** or **raw** body formats.
        Requires authentication with role in `tManager`, `fManager`, `opManager`, or `admin`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/DemandStaticsNormalized'
                - $ref: '#/components/schemas/DemandStaticsRaw'
            examples:
              normalized:
                value:
                  slotKey: "monday-afternoon"
                  items:
                    - { itemId: "68960284330bf1699eee8955", itemDisplayName: "Lettuce Romaine", averageDemandQuantityKg: 42.5 }
              raw:
                value:
                  monday-afternoon:
                    items:
                      - { itemId: "68960284330bf1699eee8955", itemDisplayName: "Lettuce Romaine", averageDemandQuantityKg: 42.5 }
      responses:
        "201":
          description: Created slot
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DemandStaticsNormalized' }
        "400":
          description: Validation error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        "409":
          description: Slot already exists
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

    put:
      tags: [DemandStatics]
      summary: Upsert a demand statics slot
      description: >
        Upserts (creates or replaces) a slot by `slotKey`.
        Accepts **normalized** or **raw** body.
        Requires authentication with role in `tManager`, `fManager`, `opManager`, or `admin`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/DemandStaticsNormalized'
                - $ref: '#/components/schemas/DemandStaticsRaw'
      responses:
        "200":
          description: Updated or created slot
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DemandStaticsNormalized' }
        "400":
          description: Validation error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /demand-statics/{slotKey}:
    get:
      tags: [DemandStatics]
      summary: Get a slot by key
      description: >
        Returns a single slot document for the specified `slotKey`.
        Public route (optional authentication).
      parameters:
        - $ref: '#/components/parameters/SlotKeyParam'
      responses:
        "200":
          description: Slot found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DemandStaticsNormalized' }
        "404":
          description: Slot not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

    delete:
      tags: [DemandStatics]
      summary: Delete a slot
      description: >
        Deletes the specified slot by `slotKey`.
        Requires authentication with role in `tManager`, `fManager`, `opManager`, or `admin`.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SlotKeyParam'
      responses:
        "200":
          description: Deleted slot document
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted:
                    type: object
                    nullable: true
                    additionalProperties: true
        "404":
          description: Slot not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /demand-statics/{slotKey}/items:
    patch:
      tags: [DemandStatics]
      summary: Replace items for a slot
      description: >
        Replaces all `items` of the specified slot.
        Requires authentication with role in `tManager`, `fManager`, `opManager`, or `admin`.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SlotKeyParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [items]
              properties:
                items:
                  type: array
                  items: { $ref: '#/components/schemas/DemandItemLine' }
      responses:
        "200":
          description: Updated slot
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DemandStaticsNormalized' }
        "400":
          description: Invalid body
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
        "404":
          description: Slot not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /demand-statics/import:
    post:
      tags: [DemandStatics]
      summary: Bulk import demand statics
      description: >
        Bulk upserts multiple demand statics slots.
        Accepts an array of **normalized** and/or **raw** objects.
        Requires authentication with role in `tManager`, `fManager`, `opManager`, or `admin`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              items:
                oneOf:
                  - $ref: '#/components/schemas/DemandStaticsNormalized'
                  - $ref: '#/components/schemas/DemandStaticsRaw'
      responses:
        "200":
          description: Bulk import summary
          content:
            application/json:
              schema:
                type: object
                required: [upserted, modified, matched]
                properties:
                  upserted: { type: integer, minimum: 0 }
                  modified: { type: integer, minimum: 0 }
                  matched: { type: integer, minimum: 0 }
        "400":
          description: Invalid input
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

  /demand-statics/{slotKey}/raw:
    get:
      tags: [DemandStatics]
      summary: Get a raw slot document
      description: >
        Returns the raw shape `{ "<slotKey>": { items: [...] } }`.
        Public route (optional authentication).
      parameters:
        - $ref: '#/components/parameters/SlotKeyParam'
      responses:
        "200":
          description: Raw slot document
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DemandStaticsRaw' }
        "404":
          description: Slot not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    SlotKeyParam:
      in: path
      name: slotKey
      required: true
      schema: { $ref: '#/components/schemas/SlotKey' }
      description: "Slot key in the form `<day>-<part>` (e.g., `monday-afternoon`)."

  schemas:
    DayName:
      type: string
      enum: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
    PartName:
      type: string
      enum: [morning, afternoon, night]
    SlotKey:
      type: string
      pattern: '^(monday|tuesday|wednesday|thursday|friday|saturday|sunday)-(morning|afternoon|night)$'
      example: monday-afternoon

    DemandItemLine:
      type: object
      required: [itemId, averageDemandQuantityKg]
      properties:
        itemId:
          type: string
          description: "Item ID reference."
        itemDisplayName:
          type: string
          nullable: true
          description: "Optional denormalized label."
        averageDemandQuantityKg:
          type: number
          minimum: 0
          description: "Average demand quantity in kilograms."
      example:
        itemId: "68960284330bf1699eee8955"
        itemDisplayName: "Lettuce Romaine"
        averageDemandQuantityKg: 42.5

    DemandStaticsNormalized:
      type: object
      required: [slotKey, items]
      properties:
        slotKey:
          $ref: '#/components/schemas/SlotKey'
        items:
          type: array
          items: { $ref: '#/components/schemas/DemandItemLine' }

    DemandStaticsRaw:
      type: object
      description: "Raw dynamic-key format."
      additionalProperties:
        type: object
        required: [items]
        properties:
          items:
            type: array
            items: { $ref: '#/components/schemas/DemandItemLine' }

    ListSlotsResponse:
      type: object
      required: [items, page, limit, total, pages]
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/DemandStaticsNormalized' }
        page: { type: integer, minimum: 1 }
        limit: { type: integer, minimum: 1, maximum: 100 }
        total: { type: integer, minimum: 0 }
        pages: { type: integer, minimum: 1 }

    Error:
      type: object
      properties:
        error:
          type: string
        details:
          oneOf:
            - type: string
            - type: array
              items: { type: string }
      example:
        error: "Unauthorized"
