openapi: 3.0.3
info:
  title: Farmer Orders API
  version: 1.0.0
  description: |
    Endpoints for creating Farmer Orders and updating their statuses and stages.
    Auth: Bearer JWT. Roles used: farmer, farmerManager, admin.

paths:
  /farmer-orders:
    post:
      summary: Create a new Farmer Order
      description: Only roles **farmerManager** or **admin** can create.
      security:
        - bearerAuth: []
      tags: [FarmerOrders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFarmerOrderRequest'
            examples:
              createExample:
                value:
                  itemId: "68960284330bf1699eee8955"
                  type: "leafy"
                  variety: "Romaine"
                  pictureUrl: "https://img.example.com/romaine.jpg"
                  farmerId: "66f3b1aa0a8c0f0012345678"
                  farmerName: "Levy Cohen"
                  farmName: "Levy Family Farm"
                  landId: "66f0b0b0b0b0b0b0b0b0b0b0"
                  sectionId: "N-3"
                  shift: "morning"
                  pickUpDate: "2025-09-22"
                  forcastedQuantityKg: 120
                  sumOrderedQuantityKg: 0
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarmerOrderResponse'
        '400':
          description: Validation failed (business or schema)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '403':
          description: Forbidden (role)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '401':
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

  /farmer-orders/{id}/farmer-status:
    patch:
      summary: Update farmerStatus (farmer/self OR manager/admin)
      description: |
        Roles:
        - **farmer** may update only if `user.id === order.farmerId`
        - **farmerManager** or **admin** may update any order

        Side effects:
        - When status = **ok**:
          - stage `farmerAck` -> `ok`, then `done`
          - stage `farmerQSrep` -> `current`
          - upsert item into Available Market Stock (by LC + date + shift)
          - audit entries added
        - When status = **problem**:
          - pipeline halted; any `current` stage cleared to `pending`
          - stage `farmerAck` -> `done` (HALT note)
          - audit entries added
      security:
        - bearerAuth: []
      tags: [FarmerOrders]
      parameters:
        - name: id
          in: path
          required: true
          description: FarmerOrder document id
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UpdateFarmerStatusRequest' }
            examples:
              okExample:
                value: { status: "ok", note: "Ready for pickup." }
              problemExample:
                value: { status: "problem", note: "Weather damage reported." }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarmerOrderResponse'
        '400':
          description: Validation failed / bad input
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '403':
          description: Forbidden (not owner farmer, or pipeline halted rules)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '404':
          description: Order not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '401':
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

  /farmer-orders/{id}/stage:
    patch:
      summary: Update a stage status (manager/admin only)
      description: |
        Allowed actions: `setCurrent`, `ok`, `done`, `problem`.

        Rules:
        - Only **farmerManager** or **admin**.
        - If pipeline halted (`farmerStatus = problem`), only `action = problem` is allowed.
        - Uses model instance methods for `setCurrent`/`ok`/`done`.
        - For `problem`, the stage entry is flagged with status `"problem"` and audited.
      security:
        - bearerAuth: []
      tags: [FarmerOrders]
      parameters:
        - name: id
          in: path
          required: true
          description: FarmerOrder document id
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UpdateStageStatusRequest' }
            examples:
              setCurrentExample:
                value: { key: "inspection", action: "setCurrent", note: "Starting inspection" }
              okExample:
                value: { key: "recived", action: "ok", note: "Received confirmed" }
              doneExample:
                value: { key: "sorting", action: "done", note: "Sorting completed" }
              problemExample:
                value: { key: "inTransit", action: "problem", note: "Delay due to traffic" }
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FarmerOrderResponse'
        '400':
          description: Validation failed / bad input
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '403':
          description: Forbidden (role or pipeline halted)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '404':
          description: Order or stage not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }
        '401':
          description: Unauthorized
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorResponse' }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateFarmerOrderRequest:
      type: object
      required:
        - itemId
        - type
        - variety
        - pictureUrl
        - farmerId
        - farmerName
        - farmName
        - landId
        - sectionId
        - shift
        - pickUpDate
        - forcastedQuantityKg
      properties:
        itemId: { type: string, description: "Item._id (string)" }
        type: { type: string }
        variety: { type: string }
        pictureUrl: { type: string, format: uri }
        farmerId: { type: string, description: "Farmer._id" }
        farmerName: { type: string }
        farmName: { type: string }
        landId: { type: string, description: "FarmerLand._id" }
        sectionId: { type: string }
        shift:
          type: string
          enum: [morning, afternoon, evening, night]
        pickUpDate:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
          example: "2025-09-22"
        forcastedQuantityKg:
          type: number
          minimum: 0
        sumOrderedQuantityKg:
          type: number
          minimum: 0
          default: 0

    UpdateFarmerStatusRequest:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [pending, ok, problem]
        note:
          type: string
          maxLength: 2000

    UpdateStageStatusRequest:
      type: object
      required: [key, action]
      properties:
        key:
          type: string
          description: "Stage key; must be one of FARMER_ORDER_STAGE_KEYS"
          enum: [farmerAck, farmerQSrep, loadedToTruck, inTransit, recived, inspection, sorting, atWarehouse]
        action:
          type: string
          enum: [setCurrent, ok, done, problem]
        note:
          type: string
          maxLength: 2000

    FarmerOrderResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/FarmerOrder'

    FarmerOrder:
      type: object
      properties:
        id: { type: string }
        createdAt: { type: string, format: date-time }
        createdBy: { type: string }
        updatedAt: { type: string, format: date-time }
        updatedBy: { type: string }
        itemId: { type: string }
        type: { type: string }
        variety: { type: string }
        pictureUrl: { type: string }
        farmerId: { type: string }
        farmerName: { type: string }
        farmName: { type: string }
        landId: { type: string, nullable: true }
        sectionId: { type: string }
        shift:
          type: string
          enum: [morning, afternoon, evening, night]
        pickUpDate:
          type: string
          pattern: '^\d{4}-\d{2}-\d{2}$'
        logisticCenterId:
          type: string
          description: 'Static: "66e007000000000000000001" (service-enforced)'
        farmerStatus:
          type: string
          enum: [pending, ok, problem]
        sumOrderedQuantityKg: { type: number }
        forcastedQuantityKg: { type: number }
        finalQuantityKg: { type: number, nullable: true }
        orders:
          type: array
          items:
            type: object
            properties:
              orderId: { type: string }
              allocatedQuantityKg: { type: number, nullable: true }
        containers:
          type: array
          items: { type: object }
        stages:
          type: array
          items:
            $ref: '#/components/schemas/Stage'
        farmersQSreport:
          $ref: '#/components/schemas/QSReport'
        inspectionQSreport:
          $ref: '#/components/schemas/QSReport'
        visualInspection:
          $ref: '#/components/schemas/VisualInspection'
        inspectionStatus:
          type: string
          enum: [pending, passed, failed]
        historyAuditTrail:
          type: array
          items:
            $ref: '#/components/schemas/AuditEntry'

    Stage:
      type: object
      properties:
        key:
          type: string
          enum: [farmerAck, farmerQSrep, loadedToTruck, inTransit, recived, inspection, sorting, atWarehouse]
        label: { type: string }
        status:
          type: string
          enum: [pending, ok, current, done, problem]
        expectedAt: { type: string, format: date-time, nullable: true }
        startedAt: { type: string, format: date-time, nullable: true }
        completedAt: { type: string, format: date-time, nullable: true }
        timestamp: { type: string, format: date-time }
        note: { type: string }

    QSReport:
      type: object
      nullable: true
      properties:
        overallGrade: { type: string, nullable: true }
        values:
          type: object
          additionalProperties: true

    VisualInspection:
      type: object
      nullable: true
      properties:
        status:
          type: string
          enum: [ok, problem, pending]
        note: { type: string, nullable: true }

    AuditEntry:
      type: object
      properties:
        userId: { type: string }
        action: { type: string }
        note: { type: string }
        meta:
          type: object
          additionalProperties: true
        timestamp: { type: string, format: date-time }

    ErrorResponse:
      type: object
      properties:
        error: { type: string }
        details:
          oneOf:
            - type: string
            - type: array
              items: { type: string }
