openapi: 3.0.3
info:
  title: Farmer Orders API
  version: 1.0.0
  description: >
    Endpoints for creating and managing Farmer Orders (FO), updating farmer
    acknowledgments and stage statuses, and retrieving summaries for the current
    and upcoming shifts.  
    Role-based access is enforced via Bearer auth (see `security` notes on each route).

servers:
  - url: /api
    description: Main API base path

tags:
  - name: FarmerOrders
    description: Farmer Orders (FO) lifecycle, summaries, and listings

paths:
  /farmer-orders:
    post:
      tags: [FarmerOrders]
      summary: Create a Farmer Order
      description: |
        Create a new Farmer Order.  
        **Auth:** Bearer token required.  
        **Roles:** `fManager`, `admin`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateFarmerOrderRequest"
            examples:
              create:
                value:
                  itemId: "66fabc000000000000000111"
                  type: "Lettuce"
                  variety: "Romaine"
                  pictureUrl: "https://cdn.example.com/img/romaine.jpg"
                  farmerId: "66fabc000000000000000222"
                  farmerName: "Levy Cohen"
                  farmName: "Green Valley Farm"
                  shift: "morning"
                  pickUpDate: "2025-10-20"
                  forcastedQuantityKg: 120
                  sumOrderedQuantityKg: 96
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/FarmerOrder"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalError"

  /farmer-orders/{id}/farmer-status:
    patch:
      tags: [FarmerOrders]
      summary: Update farmerStatus (acknowledgment/problem)
      description: |
        Update the FO-level `farmerStatus`.  
        - When set to **ok**: pipeline advances (marks `farmerAck` stage ok/done), and item is upserted into the matching AMS (Available Market Stock).  
        - When set to **problem**: pipeline is halted.  
        **Auth:** Bearer token required.  
        **Roles:** `farmer` (only for own FO), `fManager`, `admin`.
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/FarmerOrderIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateFarmerStatusRequest"
            examples:
              ok:
                value: { status: "ok", note: "Confirmed; ready for QS." }
              problem:
                value: { status: "problem", note: "Harvest delay due to weather." }
              pending:
                value: { status: "pending" }
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/FarmerOrder"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /farmer-orders/{id}/stage:
    patch:
      tags: [FarmerOrders]
      summary: Update stage status for a Farmer Order
      description: |
        Update stage state by key. Actions: `setCurrent`, `ok`, `done`, `problem`.  
        **Auth:** Bearer token required.  
        **Roles:** `fManager`, `admin`.  
        > Note: When pipeline is in `problem`, only `action=problem` is allowed unless pipeline is explicitly cleared.
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/FarmerOrderIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateStageStatusRequest"
            examples:
              setCurrent:
                value: { key: "farmerQSrep", action: "setCurrent", note: "Start QS phase" }
              ok:
                value: { key: "farmerQSrep", action: "ok" }
              done:
                value: { key: "loading", action: "done", note: "Loaded to truck" }
              problem:
                value: { key: "farmerAck", action: "problem", note: "Mismatch in quantities" }
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/FarmerOrder"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /farmer-orders/summary:
    get:
      tags: [FarmerOrders]
      summary: Summary for current shift + next N shifts
      description: |
        Returns a compact summary for the **current shift** (if any) and the **next N shifts** (default 5).  
        Includes counts of FO docs, `problemCount`, status breakdown (`okFO`, `pendingFO`, `problemFO`), and **distinct farmer counts** per status.  
        **Auth:** Bearer token required.  
        **Roles:** `admin`, `fManager`.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: logisticCenterId
          schema: { type: string }
          required: false
          description: >
            The LC id (ObjectId string). If omitted, server tries `(req.user).logisticCenterId`.
        - in: query
          name: count
          schema: { type: integer, minimum: 1, default: 5 }
          required: false
          description: Number of next shifts to include after the current one (if any).
      responses:
        "200":
          description: Summary payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FarmerOrdersUpcomingResponse"
              examples:
                sample:
                  value:
                    current:
                      date: "2025-10-19"
                      shiftName: "afternoon"
                      count: 8
                      problemCount: 1
                      okFO: 5
                      pendingFO: 2
                      problemFO: 1
                      okFarmers: 4
                      pendingFarmers: 2
                      problemFarmers: 1
                    next:
                      - date: "2025-10-19"
                        shiftName: "evening"
                        count: 0
                        problemCount: 0
                        okFO: 0
                        pendingFO: 0
                        problemFO: 0
                        okFarmers: 0
                        pendingFarmers: 0
                        problemFarmers: 0
                      - date: "2025-10-20"
                        shiftName: "night"
                        count: 3
                        problemCount: 0
                        okFO: 2
                        pendingFO: 1
                        problemFO: 0
                        okFarmers: 2
                        pendingFarmers: 1
                        problemFarmers: 0
                    tz: "Asia/Jerusalem"
                    lc: "66e007000000000000000001"
        "400":
            $ref: "#/components/responses/BadRequest"
        "401":
            $ref: "#/components/responses/Unauthorized"
        "403":
            $ref: "#/components/responses/Forbidden"
        "500":
            $ref: "#/components/responses/InternalError"

  /farmer-orders/by-shift:
    get:
      tags: [FarmerOrders]
      summary: List Farmer Orders for a specific (date, shift)
      description: |
        Paginated list of FO for a given **pickUpDate** (yyyy-LL-dd, LC timezone) and **shift**.  
        Supports optional filtering by `farmerStatus`.  
        **Auth:** Bearer token required.  
        **Roles:** `admin`, `fManager`.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: logisticCenterId
          schema: { type: string }
          required: false
          description: >
            The LC id (ObjectId string). If omitted, server tries `(req.user).logisticCenterId`.
        - in: query
          name: date
          schema: { type: string, pattern: "^\\d{4}-\\d{2}-\\d{2}$" }
          required: true
          description: pickUpDate in LC timezone (format `yyyy-LL-dd`)
        - in: query
          name: shiftName
          schema:
            $ref: "#/components/schemas/ShiftName"
          required: true
          description: Shift name
        - in: query
          name: farmerStatus
          schema:
            $ref: "#/components/schemas/FarmerApprovalStatus"
          required: false
          description: Optional filter on FO farmerStatus
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
          required: false
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, default: 50 }
          required: false
        - in: query
          name: fields
          schema:
            type: array
            items: { type: string }
            example: [ "farmerName", "farmName", "type", "variety", "farmerStatus" ]
          required: false
          style: form
          explode: true
          description: Optional projection fields
      responses:
        "200":
          description: OK (paginated)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FarmerOrdersByShiftResponse"
              examples:
                sample:
                  value:
                    meta:
                      lc: "66e007000000000000000001"
                      date: "2025-10-20"
                      shiftName: "morning"
                      tz: "Asia/Jerusalem"
                      page: 1
                      limit: 50
                      total: 3
                      problemCount: 1
                      pages: 1
                    items:
                      - _id: "66fabcd0000000000000aaa1"
                        farmerName: "Levy Cohen"
                        farmName: "Green Valley Farm"
                        type: "Lettuce"
                        variety: "Romaine"
                        farmerStatus: "ok"
                      - _id: "66fabcd0000000000000aaa2"
                        farmerName: "Maya Klein"
                        farmName: "Sun Farm"
                        type: "Spinach"
                        variety: "Baby"
                        farmerStatus: "pending"
                      - _id: "66fabcd0000000000000aaa3"
                        farmerName: "Yousef Haddad"
                        farmName: "Al-Nahr Farm"
                        type: "Strawberry"
                        variety: "Albion"
                        farmerStatus: "problem"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    FarmerOrderIdParam:
      in: path
      name: id
      required: true
      schema: { type: string, description: "FarmerOrder _id (ObjectId string)" }

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            validation:
              value:
                error: "Validation failed"
                details: ["field X is required"]
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            token:
              value: { error: "Unauthorized" }
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            roles:
              value:
                error: "Forbidden"
                details: ["Only farmerManager or admin can update stages"]
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            foMissing:
              value:
                error: "Not Found"
                details: ["Farmer order not found"]
    InternalError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    ShiftName:
      type: string
      enum: [morning, afternoon, evening, night]

    FarmerApprovalStatus:
      type: string
      enum: [pending, ok, problem]

    CreateFarmerOrderRequest:
      type: object
      required:
        - itemId
        - type
        - variety
        - pictureUrl
        - farmerId
        - farmerName
        - farmName
        - shift
        - pickUpDate
        - forcastedQuantityKg
      properties:
        itemId:
          type: string
          description: Item _id (ObjectId string)
        type:
          type: string
        variety:
          type: string
        pictureUrl:
          type: string
          format: uri
        farmerId:
          type: string
          description: Farmer _id (ObjectId string)
        farmerName:
          type: string
        farmName:
          type: string
        shift:
          $ref: "#/components/schemas/ShiftName"
        pickUpDate:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
          example: "2025-10-20"
        forcastedQuantityKg:
          type: number
          minimum: 0
        sumOrderedQuantityKg:
          type: number
          minimum: 0
      additionalProperties: false

    UpdateFarmerStatusRequest:
      type: object
      required: [status]
      properties:
        status:
          $ref: "#/components/schemas/FarmerApprovalStatus"
        note:
          type: string
      additionalProperties: false

    UpdateStageStatusRequest:
      type: object
      required: [key, action]
      properties:
        key:
          type: string
          description: Stage key (must exist in FO stages)
          example: farmerAck
        action:
          type: string
          enum: [setCurrent, ok, done, problem]
        note:
          type: string
      additionalProperties: false

    FarmerOrder:
      type: object
      description: >
        Farmer Order document (selected fields). Exact shape may include more fields.
      properties:
        _id:
          type: string
        itemId:
          type: string
        type:
          type: string
        variety:
          type: string
        pictureUrl:
          type: string
        farmerId:
          type: string
        farmerName:
          type: string
        farmName:
          type: string
        shift:
          $ref: "#/components/schemas/ShiftName"
        pickUpDate:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
        logisticCenterId:
          type: string
        farmerStatus:
          $ref: "#/components/schemas/FarmerApprovalStatus"
        sumOrderedQuantityKg:
          type: number
        forcastedQuantityKg:
          type: number
        finalQuantityKg:
          type: number
        inspectionStatus:
          type: string
          enum: [pending, passed, failed]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    FOSummaryEntry:
      type: object
      properties:
        date:
          type: string
          pattern: "^\\d{4}-\\d{2}-\\d{2}$"
        shiftName:
          $ref: "#/components/schemas/ShiftName"
        count:
          type: integer
          minimum: 0
        problemCount:
          type: integer
          minimum: 0
        okFO:
          type: integer
          minimum: 0
        pendingFO:
          type: integer
          minimum: 0
        problemFO:
          type: integer
          minimum: 0
        okFarmers:
          type: integer
          minimum: 0
        pendingFarmers:
          type: integer
          minimum: 0
        problemFarmers:
          type: integer
          minimum: 0

    FarmerOrdersUpcomingResponse:
      type: object
      properties:
        current:
          oneOf:
            - $ref: "#/components/schemas/FOSummaryEntry"
            - type: "null"
        next:
          type: array
          items:
            $ref: "#/components/schemas/FOSummaryEntry"
        tz:
          type: string
          example: "Asia/Jerusalem"
        lc:
          type: string
          description: Logistic Center id (ObjectId string)

    FarmerOrdersByShiftResponse:
      type: object
      properties:
        meta:
          type: object
          properties:
            lc: { type: string }
            date:
              type: string
              pattern: "^\\d{4}-\\d{2}-\\d{2}$"
            shiftName:
              $ref: "#/components/schemas/ShiftName"
            tz:
              type: string
            page:
              type: integer
              minimum: 1
            limit:
              type: integer
              minimum: 1
            total:
              type: integer
              minimum: 0
            problemCount:
              type: integer
              minimum: 0
            pages:
              type: integer
              minimum: 0
        items:
          type: array
          items:
            type: object
            description: >
              FarmerOrder projection (fields depend on `fields` query param).
            additionalProperties: true

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          oneOf:
            - type: array
              items: { type: string }
            - type: object
            - type: string
      additionalProperties: false
