openapi: 3.0.3
info:
  title: DFCP Items API
  version: 1.0.0
  description: Endpoints for items, packing, and market item page data.

servers:
  - url: /api/items

tags:
  - name: Items

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ItemId:
      name: itemId
      in: path
      required: true
      description: MongoDB ObjectId of the item.
      schema:
        type: string
        pattern: '^[a-fA-F0-9]{24}$'
    FarmerUserId:
      name: farmerUserId
      in: path
      required: true
      description: MongoDB ObjectId of the farmer's **User** document.
      schema:
        type: string
        pattern: '^[a-fA-F0-9]{24}$'
    IncludePacking:
      name: includePacking
      in: query
      required: false
      description: For privileged roles (admin, fManager) only — return the joined item+packing view.
      schema:
        type: boolean

  schemas:
    ApiError:
      type: object
      properties:
        error:
          type: string
          example: ValidationError
        message:
          type: string
        details:
          type: array
          items:
            type: string

    PaginationMeta:
      type: object
      properties:
        page: { type: integer, minimum: 1 }
        limit: { type: integer, minimum: 1 }
        total: { type: integer, minimum: 0 }
        pages: { type: integer, minimum: 0 }

    ItemCategory:
      type: string
      enum: [fruit, vegetable, egg_dairy, other]

    Price:
      type: object
      properties:
        a: { type: number, nullable: true, minimum: 0, description: Base price per KG }
        b: { type: number, nullable: true, minimum: 0 }
        c: { type: number, nullable: true, minimum: 0 }

    SellModes:
      type: object
      properties:
        byKg: { type: boolean, default: true }
        byUnit: { type: boolean, default: false }
        unitBundleSize: { type: integer, minimum: 1, default: 1 }

    ItemBase:
      type: object
      properties:
        _id:
          type: string
          description: Item id (ObjectId as string)
          example: "68960284330bf1699eee8956"
        category:
          $ref: '#/components/schemas/ItemCategory'
        type: { type: string, example: "Cucumber" }
        variety: { type: string, nullable: true, example: "Persian" }
        imageUrl: { type: string, nullable: true, format: uri }
        season: { type: string, nullable: true }
        farmerTips: { type: string, nullable: true }
        customerInfo:
          type: array
          items: { type: string }
        caloriesPer100g: { type: number, nullable: true, minimum: 0 }
        price:
          $ref: '#/components/schemas/Price'
        avgWeightPerUnitGr: { type: number, nullable: true, minimum: 0 }
        sdWeightPerUnitGr: { type: number, minimum: 0, default: 0 }
        avgQmPerUnit: { type: number, nullable: true, minimum: 0 }
        weightPerUnitG: { type: number, nullable: true, minimum: 0 }
        sellModes:
          $ref: '#/components/schemas/SellModes'
        pricePerUnitOverride: { type: number, nullable: true, minimum: 0 }
        qualityStandards:
          type: object
          nullable: true
          additionalProperties: true
        tolerance:
          type: string
          description: Relative tolerance (stored as string like "0.02")
          example: "0.02"
        lastUpdated:
          type: string
          format: date-time
        # computed virtuals that may appear on responses
        name: { type: string, example: "Cucumber Persian" }
        unitMode:
          type: string
          enum: [kg, unit, mixed]
        pricePerKg:
          type: number
          nullable: true
        pricePerUnit:
          type: number
          nullable: true
        pricePerBundle:
          type: number
          nullable: true

    ItemPublic:
      description: Minimal public view
      type: object
      properties:
        _id: { type: string }
        displayName: { type: string }
        category: { $ref: '#/components/schemas/ItemCategory' }
        itemUrl: { type: string, example: "/items/68960284330bf1699eee8956" }

    PackingInfo:
      type: object
      required:
        - bulkDensityKgPerL
        - litersPerKg
        - fragility
        - allowMixing
        - requiresVentedBox
        - minBoxType
      properties:
        bulkDensityKgPerL: { type: number, minimum: 0.001 }
        litersPerKg: { type: number, minimum: 0.001, description: "≈ 1 / bulkDensityKgPerL (±8%)" }
        fragility:
          type: string
          enum: [very_fragile, fragile, normal, sturdy]
        allowMixing: { type: boolean }
        requiresVentedBox: { type: boolean }
        minBoxType:
          type: string
          description: PackageSize.key
          example: "BOX_M"
        maxWeightPerBoxKg: { type: number, nullable: true, minimum: 0.001 }
        notes: { type: string, nullable: true }

    ItemWithPacking:
      allOf:
        - $ref: '#/components/schemas/ItemBase'
        - type: object
          properties:
            packing:
              $ref: '#/components/schemas/PackingInfo'

    CreateItemWithPackingBody:
      allOf:
        - $ref: '#/components/schemas/ItemBase'
        - type: object
          required: [category, type, packing]
          properties:
            packing:
              $ref: '#/components/schemas/PackingInfo'
      example:
        category: vegetable
        type: Cucumber
        variety: Persian
        price: { a: 12.5 }
        sellModes: { byKg: true, byUnit: true, unitBundleSize: 1 }
        avgWeightPerUnitGr: 120
        packing:
          bulkDensityKgPerL: 0.65
          litersPerKg: 1.54
          fragility: normal
          allowMixing: true
          requiresVentedBox: false
          minBoxType: BOX_M
          notes: "Do not overpack; keep cool."

    ListItemsResponsePublic:
      type: object
      allOf:
        - $ref: '#/components/schemas/PaginationMeta'
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemPublic'

    ListItemsResponsePriv:
      type: object
      allOf:
        - $ref: '#/components/schemas/PaginationMeta'
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemWithPacking'

    DeletePrivilegedResponse:
      type: object
      properties:
        deleted: { type: boolean, example: true }
        item:
          anyOf:
            - $ref: '#/components/schemas/ItemWithPacking'
            - type: "null"

    ItemBenefits:
      type: object
      properties:
        data:
          type: object
          properties:
            customerInfo:
              type: array
              items: { type: string }
            caloriesPer100g:
              type: number
              nullable: true

    MarketItemPage:
      type: object
      properties:
        data:
          type: object
          properties:
            item:
              type: object
              properties:
                customerInfo:
                  type: array
                  items: { type: string }
                caloriesPer100g:
                  type: number
                  nullable: true
            farmer:
              type: object
              properties:
                logo: { type: string, nullable: true }
                farmName: { type: string }
                farmLogo: { type: string, nullable: true }
                farmerBio: { type: string, nullable: true }

paths:
  /:
    get:
      tags: [Items]
      summary: List items
      description: >
        Public listing (unauthenticated or non-privileged) returns minimal public items.
        Privileged users (admin, fManager) receive full items joined with `packing`.
      security: []  # authenticateIfPresent
      parameters:
        - name: category
          in: query
          required: false
          schema: { $ref: '#/components/schemas/ItemCategory' }
        - name: type
          in: query
          schema: { type: string }
        - name: variety
          in: query
          schema: { type: string }
        - name: q
          in: query
          schema: { type: string }
        - name: minCalories
          in: query
          schema: { type: number }
        - name: maxCalories
          in: query
          schema: { type: number }
        - name: page
          in: query
          schema: { type: integer, minimum: 1, default: 1 }
        - name: limit
          in: query
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
        - name: sort
          in: query
          schema:
            type: string
            description: Comma-separated fields; prefix with '-' for desc (e.g. "-updatedAt,type")
      responses:
        '200':
          description: Items list
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ListItemsResponsePublic'
                  - $ref: '#/components/schemas/ListItemsResponsePriv'
    post:
      tags: [Items]
      summary: Create item (with packing)
      description: >
        Privileged only (admin, fManager). Body must contain `packing` object.
        If `includePacking=true` is provided and caller is privileged, the joined view is returned.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/IncludePacking'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateItemWithPackingBody'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemWithPacking'
                  - type: object
                    description: Legacy shape (item plus convenience packing snapshot).
                    properties:
                      _id: { type: string }
                      # ...other ItemBase fields possible
                      packing:
                        $ref: '#/components/schemas/PackingInfo'
        '400':
          description: Validation error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /benefits/{itemId}:
    get:
      tags: [Items]
      summary: Item benefits (market helper)
      description: Returns customer info and calories for a given item.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ItemId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ItemBenefits' }
        '400':
          description: Invalid itemId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /marketItemPage/{itemId}/{farmerUserId}:
    get:
      tags: [Items]
      summary: Market item page data
      description: Aggregated item + farmer bio block for the market item page.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ItemId'
        - $ref: '#/components/parameters/FarmerUserId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/MarketItemPage' }
        '400':
          description: Invalid ids
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '401':
          description: Unauthorized
        '404':
          description: Not found

  /{itemId}:
    get:
      tags: [Items]
      summary: Get item by id
      description: >
        Public/unauthenticated returns a minimal public object.
        Privileged (admin, fManager) always receive the joined item+packing view.
      security: []  # authenticateIfPresent
      parameters:
        - $ref: '#/components/parameters/ItemId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemPublic'
                  - $ref: '#/components/schemas/ItemWithPacking'
        '400':
          description: Invalid itemId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '404':
          description: Not found
    patch:
      tags: [Items]
      summary: Patch item (partial update)
      description: Privileged only (admin, fManager). Optionally `includePacking=true` to return joined view.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ItemId'
        - $ref: '#/components/parameters/IncludePacking'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Partial item fields to update. `_id` (if provided) must match path.
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemWithPacking'
                  - $ref: '#/components/schemas/ItemBase'
        '400':
          description: Validation or id mismatch
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
    put:
      tags: [Items]
      summary: Replace item (idempotent)
      description: Privileged only (admin, fManager). Returns joined view for privileged callers.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ItemId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemBase'
      responses:
        '200':
          description: Replaced
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemWithPacking'
                  - $ref: '#/components/schemas/ItemPublic'
        '400':
          description: Validation or id mismatch
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiError' }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
    delete:
      tags: [Items]
      summary: Delete item
      description: >
        Privileged only (admin).  
        Non-privileged behavior does not apply. For privileged users, response is 200 with a snapshot; otherwise controller may return 204.
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ItemId'
      responses:
        '200':
          description: Deleted (privileged snapshot)
          content:
            application/json:
              schema: { $ref: '#/components/schemas/DeletePrivilegedResponse' }
        '204':
          description: Deleted (no content)
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
