openapi: 3.0.3
info:
  title: Items API
  version: 1.1.0

tags:
  - name: Items
    description: Catalog of items (produce). Public GETs support optional auth; privileged fields require admin/fManager.

paths:
  /items:
    get:
      tags: [Items]
      summary: List items (public; optional auth). If authenticated as admin/fManager returns full items; otherwise public view.
      description: |
        Public route with *optional* auth (admin/fManager).  
        - **Unauthenticated** → returns public projection (minimal fields).  
        - **Authenticated (admin or fManager)** → returns full items.
      parameters:
        - in: query
          name: category
          schema:
            type: string
            enum: [fruit, vegetable]
          description: Filter by category
        - in: query
          name: type
          schema: { type: string }
        - in: query
          name: variety
          schema: { type: string }
        - in: query
          name: q
          schema: { type: string }
          description: Free-text search across type/variety
        - in: query
          name: minCalories
          schema: { type: number }
        - in: query
          name: maxCalories
          schema: { type: number }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
        - in: query
          name: sort
          schema: { type: string, example: "-updatedAt" }
          description: Comma-separated fields; prefix with '-' for desc
      responses:
        '200':
          description: Paginated items
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemListPublicResponse'
                  - $ref: '#/components/schemas/ItemListPrivilegedResponse'
              examples:
                public:
                  summary: Public response
                  value:
                    items:
                      - _id: "66ef1f2e5d8f7a0012ab34cd"
                        displayName: "Apple Fuji"
                        category: "fruit"
                        itemUrl: "/items/66ef1f2e5d8f7a0012ab34cd"
                    page: 1
                    limit: 20
                    total: 1
                    pages: 1
                privileged:
                  summary: Privileged response
                  value:
                    items:
                      - _id: "66ef1f2e5d8f7a0012ab34cd"
                        type: "Apple"
                        variety: "Fuji"
                        category: "fruit"
                        caloriesPer100g: 52
                        customerInfo: ["High in vitamin C"]
                        price: { a: 2.5, b: 2, c: 1.5 }
                        sellModes: { byKg: true, byUnit: true, unitBundleSize: 1 }
                        avgWeightPerUnitGr: 180
                        sdWeightPerUnitGr: 20
                        tolerance: "0.02"
                        createdAt: "2025-09-21T08:00:00.000Z"
                        updatedAt: "2025-10-02T13:00:00.000Z"
                    page: 1
                    limit: 20
                    total: 1
                    pages: 1
    post:
      tags: [Items]
      summary: Create a new item (admin/fManager)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ItemCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemFull'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /items/{itemId}:
    get:
      tags: [Items]
      summary: Get an item by ID (public; optional auth)
      description: |
        Public route with *optional* auth.
        - **Unauthenticated** → returns public projection.
        - **Authenticated (admin/fManager)** → returns full item.
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      responses:
        '200':
          description: Item
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ItemPublic'
                  - $ref: '#/components/schemas/ItemFull'
        '400':
          description: Invalid itemId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "Invalid itemId" }
        '404':
          description: Item not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "Item not found" }
    patch:
      tags: [Items]
      summary: Partially update an item (admin/fManager)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemPatch'
      responses:
        '200':
          description: Updated item
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ItemFull' }
        '400':
          description: Invalid itemId or body
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Item not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
    put:
      tags: [Items]
      summary: Replace an item (admin/fManager)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/ItemCreate'
      responses:
        '200':
          description: Replaced item
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ItemFull' }
        '400':
          description: Invalid itemId or body
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Item not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
    delete:
      tags: [Items]
      summary: Delete an item (admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      responses:
        '204':
          description: Deleted
        '400':
          description: Invalid itemId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Item not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }

  /items/benefits/{itemId}:
    get:
      tags: [Items]
      summary: Get item benefits (customer info + calories per 100g)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: itemId
          required: true
          description: The MongoDB ObjectId of the item
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      responses:
        '200':
          description: Item benefits
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/ItemBenefits'
              example:
                data:
                  customerInfo: ["High in vitamin C", "Good for immunity"]
                  caloriesPer100g: 52
        '400':
          description: Invalid itemId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "Invalid itemId" }
        '404':
          description: Item not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "Item not found" }

  /items/marketItemPage/{itemId}/{farmerUserId}:
    get:
      tags: [Items]
      summary: Get both item benefits and farmer bio for the market item page
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: itemId
          required: true
          description: The MongoDB ObjectId of the item
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
        - in: path
          name: farmerUserId
          required: true
          description: The MongoDB ObjectId of the farmer's linked User
          schema:
            type: string
            pattern: '^[a-fA-F0-9]{24}$'
      responses:
        '200':
          description: Combined item and farmer info
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/MarketItemPageData'
              example:
                data:
                  item:
                    customerInfo: ["High in vitamin C", "Good for immunity"]
                    caloriesPer100g: 52
                  farmer:
                    logo: "https://example.com/user-logo.png"
                    farmName: "Green Valley Farm"
                    farmLogo: "https://example.com/farm-logo.png"
                    farmerBio: "Third-generation farmer specializing in organic apples."
        '400':
          description: Invalid itemId or farmerUserId
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "itemId and farmerUserId are required and must be valid ObjectIds" }
        '404':
          description: Item or Farmer not found
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ErrorMessage' }
              example: { message: "Item or Farmer not found" }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # ---------- Core item shapes ----------
    Price:
      type: object
      properties:
        a: { type: number, minimum: 0, nullable: true, description: Base price per KG }
        b: { type: number, minimum: 0, nullable: true }
        c: { type: number, minimum: 0, nullable: true }

    SellModes:
      type: object
      properties:
        byKg: { type: boolean, default: true }
        byUnit: { type: boolean, default: false }
        unitBundleSize: { type: integer, minimum: 1, default: 1 }

    QualityStandards:
      type: object
      description: Quality/tolerance descriptors (free-form strings per grade).
      properties:
        brix:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        acidityPercentage:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        pressure:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        colorDescription:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        colorPercentage:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        weightPerUnitG:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        diameterMM:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        qualityGrade:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        maxDefectRatioLengthDiameter:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }
        rejectionRate:
          type: object
          properties: { A: {type: string}, B: {type: string}, C: {type: string} }

    ItemBase:
      type: object
      properties:
        _id: { type: string }
        type: { type: string }
        variety: { type: string, nullable: true }
        category:
          type: string
          enum: [fruit, vegetable]
        imageUrl: { type: string, nullable: true, format: uri }
        season: { type: string, nullable: true }
        farmerTips: { type: string, nullable: true }
        customerInfo:
          type: array
          items: { type: string }
          default: []
        caloriesPer100g: { type: number, minimum: 0, nullable: true }
        price:
          $ref: '#/components/schemas/Price'
        avgWeightPerUnitGr: { type: number, minimum: 0, nullable: true }
        sdWeightPerUnitGr: { type: number, minimum: 0, default: 0 }
        avgQmPerUnit: { type: number, minimum: 0, nullable: true }
        weightPerUnitG: { type: number, minimum: 0, nullable: true, description: Legacy alias for avgWeightPerUnitGr }
        sellModes: { $ref: '#/components/schemas/SellModes' }
        pricePerUnitOverride: { type: number, minimum: 0, nullable: true }
        qualityStandards: { $ref: '#/components/schemas/QualityStandards' }
        tolerance:
          type: string
          example: "0.02"
          description: Decimal fraction as string (e.g. "0.02" for ±2%)
        lastUpdated: { type: string, format: date-time }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }

    ItemFull:
      allOf:
        - $ref: '#/components/schemas/ItemBase'

    ItemCreate:
      type: object
      required: [category, type, variety]
      properties:
        category:
          type: string
          enum: [fruit, vegetable]
        type: { type: string }
        variety: { type: string }
        imageUrl: { type: string, nullable: true, format: uri }
        season: { type: string, nullable: true }
        farmerTips: { type: string, nullable: true }
        customerInfo:
          type: array
          items: { type: string }
        caloriesPer100g: { type: number, minimum: 0, nullable: true }
        price:
          $ref: '#/components/schemas/Price'
        avgWeightPerUnitGr: { type: number, minimum: 0, nullable: true }
        sdWeightPerUnitGr: { type: number, minimum: 0 }
        avgQmPerUnit: { type: number, minimum: 0, nullable: true }
        weightPerUnitG: { type: number, minimum: 0, nullable: true }
        sellModes: { $ref: '#/components/schemas/SellModes' }
        pricePerUnitOverride: { type: number, minimum: 0, nullable: true }
        qualityStandards: { $ref: '#/components/schemas/QualityStandards' }
        tolerance:
          type: string
          example: "0.02"
        lastUpdated: { type: string, format: date-time }

    ItemPatch:
      type: object
      description: Any subset of fields from ItemCreate
      properties:
        category: { type: string, enum: [fruit, vegetable] }
        type: { type: string }
        variety: { type: string }
        imageUrl: { type: string, nullable: true, format: uri }
        season: { type: string, nullable: true }
        farmerTips: { type: string, nullable: true }
        customerInfo:
          type: array
          items: { type: string }
        caloriesPer100g: { type: number, minimum: 0, nullable: true }
        price: { $ref: '#/components/schemas/Price' }
        avgWeightPerUnitGr: { type: number, minimum: 0, nullable: true }
        sdWeightPerUnitGr: { type: number, minimum: 0 }
        avgQmPerUnit: { type: number, minimum: 0, nullable: true }
        weightPerUnitG: { type: number, minimum: 0, nullable: true }
        sellModes: { $ref: '#/components/schemas/SellModes' }
        pricePerUnitOverride: { type: number, minimum: 0, nullable: true }
        qualityStandards: { $ref: '#/components/schemas/QualityStandards' }
        tolerance:
          type: string
          example: "0.02"

    ItemPublic:
      type: object
      description: Public projection for unauthenticated users
      properties:
        _id: { type: string }
        displayName: { type: string }
        category: { type: string, enum: [fruit, vegetable] }
        itemUrl: { type: string }

    # ---------- List response wrappers ----------
    ItemListPublicResponse:
      type: object
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/ItemPublic' }
        page: { type: integer }
        limit: { type: integer }
        total: { type: integer }
        pages: { type: integer }

    ItemListPrivilegedResponse:
      type: object
      properties:
        items:
          type: array
          items: { $ref: '#/components/schemas/ItemFull' }
        page: { type: integer }
        limit: { type: integer }
        total: { type: integer }
        pages: { type: integer }

    # ---------- Market page specific ----------
    ItemBenefits:
      type: object
      properties:
        customerInfo:
          type: array
          items: { type: string }
        caloriesPer100g:
          type: number
          nullable: true

    FarmerBio:
      type: object
      properties:
        logo: { type: string, nullable: true }
        farmName: { type: string }
        farmLogo: { type: string, nullable: true }
        farmerBio: { type: string, nullable: true }

    MarketItemPageData:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/ItemBenefits'
        farmer:
          $ref: '#/components/schemas/FarmerBio'

    # ---------- Errors ----------
    ErrorMessage:
      type: object
      required: [message]
      properties:
        message: { type: string }
