openapi: 3.0.3
info:
  title: Orders API
  version: "1.0.0"
  description: >
    Endpoints for creating and managing customer orders.

    Notes:
      - All endpoints require authentication (JWT bearer).
      - `logisticsCenterId` is **server-assigned** (derived from tenant/config or address)
        and is exposed in responses as `logisticsCenterId` (read-only).
      - `GET /orders?currentShift=1` is gated:
          * `admin`/`tManager` can view all orders in the active shift.
          * `deliverer`/`industrialDeliverer` are forced to their own assignments for the active shift.
          * `customer` is forced to their own orders for the active shift.
          * Other staff (e.g. `opManager`, `fManager`) receive **403** when using `currentShift`.
      - Deliverer status transitions allowed:
          * `ready → out_for_delivery | problem`
          * `out_for_delivery → delivered | problem`

tags:
  - name: Orders
    description: Customer orders

servers:
  - url: /api

paths:
  /orders:
    post:
      tags: [Orders]
      summary: Create a new order (customers only)
      description: >
        Creates an order for the authenticated customer.
        The server calculates `itemsSubtotal`, sets a fixed `deliveryFee`, calculates `totalPrice`
        and `totalOrderWeightKg`, and assigns `logisticsCenterId`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderInput'
            examples:
              simple:
                value:
                  deliveryAddress:
                    line1: "123 Market St"
                    city: "Haifa"
                    country: "IL"
                  items:
                    - itemId: "apple-1"
                      name: "Apples"
                      pricePerUnit: 3.5
                      quantity: 2
                      sourceFarmerName: "Levi"
                      sourceFarmName: "Green Valley"
                      farmerOrderId: "66ef1fa65d8f7a0012ab35fe"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
              example:
                data:
                  _id: 66ef1f2e5d8f7a0012ab34cd
                  customerId: 66ef1e7c5d8f7a0012ab3400
                  deliveryAddress:
                    line1: "123 Market St"
                    city: "Haifa"
                    country: "IL"
                  logisticsCenterId: "66e007000000000000000001"
                  items:
                    - itemId: "apple-1"
                      name: "Apples"
                      pricePerUnit: 3.5
                      quantity: 2
                      sourceFarmerName: "Levi"
                      sourceFarmName: "Green Valley"
                      farmerOrderId: "66ef1fa65d8f7a0012ab35fe"
                  itemsSubtotal: 7
                  deliveryFee: 15
                  totalPrice: 22
                  totalOrderWeightKg: 2
                  status: "pending"
                  assignedDelivererId: null
                  historyAuditTrail: []
                  createdAt: "2025-09-14T10:00:00.000Z"
                  updatedAt: "2025-09-14T10:00:00.000Z"
        '400':
          description: Bad request (e.g., missing deliveryAddress or empty items[])
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (role not allowed)

    get:
      tags: [Orders]
      summary: List orders with rich filters (staff can see all; customers see their own)
      description: >
        Supports pagination, sorting, item-level filters, numeric ranges, and shift scoping.

        Special behavior:
          - If `currentShift=1`, role-based gating is enforced (see top-level Notes).
          - Without `currentShift`, couriers default to their own `assignedDelivererId` unless overridden.
          - Customers are always scoped to their own orders.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema: { type: string }
          description: "Single or comma-separated (e.g. ready,out_for_delivery)"
        - in: query
          name: customerId
          schema: { type: string }
          description: "Staff only; customers are forced to their own ID"
        - in: query
          name: assignedDelivererId
          schema: { type: string, nullable: true }
        - in: query
          name: logisticsCenterId
          schema: { type: string }
          description: "Optional LC scope; also used when `currentShift=1` to find the active shift window"
        - in: query
          name: from
          schema: { type: string, format: date-time }
        - in: query
          name: to
          schema: { type: string, format: date-time }
        - in: query
          name: currentShift
          schema: { type: boolean }
          description: "Use active shift window (role-gated; may return 403 for some staff)"
        - in: query
          name: shiftStart
          schema: { type: string, format: date-time }
        - in: query
          name: shiftEnd
          schema: { type: string, format: date-time }
        - in: query
          name: date
          schema: { type: string }
          description: "YYYY-MM-DD; used with 'shift' convenience"
        - in: query
          name: shift
          schema: { type: string, enum: [morning, afternoon, evening, night] }
          description: "Convenience; used with 'date' when shiftStart/shiftEnd not provided"
        - in: query
          name: itemId
          schema: { type: string }
        - in: query
          name: farmerOrderId
          schema: { type: string }
        - in: query
          name: category
          schema: { type: string }
        - in: query
          name: sourceFarmName
          schema: { type: string }
        - in: query
          name: sourceFarmerName
          schema: { type: string }
        - in: query
          name: minTotal
          schema: { type: number }
        - in: query
          name: maxTotal
          schema: { type: number }
        - in: query
          name: minWeight
          schema: { type: number }
        - in: query
          name: maxWeight
          schema: { type: number }
        - in: query
          name: page
          schema: { type: integer, minimum: 1, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
        - in: query
          name: sort
          schema: { type: string, example: "-createdAt" }
      responses:
        '200':
          description: Paginated list of orders
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/PaginatedOrders'
        '400':
          description: Invalid status filter
        '401':
          description: Unauthorized
        '403':
          description: Forbidden when using currentShift without required role

  /orders/my:
    get:
      tags: [Orders]
      summary: List orders for the authenticated customer
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: limit
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: Paginated list of the user's orders
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/PaginatedOrders'
        '401':
          description: Unauthorized

  /orders/{id}:
    get:
      tags: [Orders]
      summary: Get a single order by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not owner/staff/courier)
        '404':
          description: Not found

    patch:
      tags: [Orders]
      summary: Update general fields (owner early-stage or staff)
      description: >
        Allowed fields: `deliveryAddress`, `items`, `assignedDelivererId`, `customerDeliveryId`.

        Customers can only modify while order status is **pending** or **confirmed**.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderInput'
      responses:
        '200':
          description: Updated order
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Customer cannot modify after preparation
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not owner/staff)

  /orders/{id}/status:
    patch:
      tags: [Orders]
      summary: Set order status (deliverers limited; staff unrestricted)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetStatusInput'
      responses:
        '200':
          description: Updated order with new status
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Invalid transition or status
        '401':
          description: Unauthorized
        '403':
          description: Not allowed for deliverer (violates allowed transition)

  /orders/{id}/assign-deliverer:
    patch:
      tags: [Orders]
      summary: Assign or unassign a deliverer (opManager/tManager/admin)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignDelivererInput'
      responses:
        '200':
          description: Updated order
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (role not allowed)

  /orders/{id}/audit:
    post:
      tags: [Orders]
      summary: Append an audit entry to the order
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [action]
              properties:
                action: { type: string }
                note: { type: string }
                meta:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: Order with new audit entry
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '400':
          description: action is required
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not owner/staff/courier/farmer)

  /orders/{id}/cancel:
    post:
      tags: [Orders]
      summary: Cancel an order (owner or staff)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Order canceled
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Cannot cancel terminal order
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not owner/staff)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Address:
      type: object
      properties:
        line1: { type: string }
        line2: { type: string }
        city: { type: string }
        state: { type: string }
        postalCode: { type: string }
        country: { type: string }

    AuditEntry:
      type: object
      properties:
        userId: { type: string }
        action: { type: string }
        note: { type: string }
        meta: { type: object, additionalProperties: true }
        timestamp: { type: string, format: date-time }

    OrderItem:
      type: object
      required: [itemId, name, pricePerUnit, quantity, sourceFarmerName, sourceFarmName, farmerOrderId]
      properties:
        itemId: { type: string }
        name: { type: string }
        imageUrl: { type: string }
        pricePerUnit: { type: number, minimum: 0 }
        quantity: { type: number, minimum: 0.1, description: "kg or units" }
        category: { type: string }
        sourceFarmerName: { type: string }
        sourceFarmName: { type: string }
        farmerOrderId: { type: string }

    Order:
      type: object
      required:
        [customerId, deliveryAddress, items, itemsSubtotal, deliveryFee, totalPrice, totalOrderWeightKg, status, logisticsCenterId]
      properties:
        _id: { type: string }
        customerId: { type: string }
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        logisticsCenterId:
          type: string
          description: "Server-assigned; exposed in API as lowerCamelCase"
          readOnly: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        itemsSubtotal: { type: number, readOnly: true }
        deliveryFee: { type: number, readOnly: true, description: "Fixed at 15" }
        totalPrice: { type: number, readOnly: true }
        totalOrderWeightKg: { type: number, readOnly: true }
        status:
          type: string
          enum: [pending, confirmed, preparing, ready, out_for_delivery, delivered, canceled, problem]
        assignedDelivererId: { type: string, nullable: true }
        customerDeliveryId: { type: string, nullable: true }
        historyAuditTrail:
          type: array
          items:
            $ref: '#/components/schemas/AuditEntry'
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }

    PaginatedOrders:
      type: object
      required: [items, page, limit, total, pages]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        page: { type: integer }
        limit: { type: integer }
        total: { type: integer }
        pages: { type: integer }

    CreateOrderInput:
      type: object
      required: [deliveryAddress, items]
      properties:
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItem'
      description: >
        `logisticsCenterId` is ignored if provided and set on the server.

    UpdateOrderInput:
      type: object
      properties:
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        assignedDelivererId:
          type: string
          nullable: true
        customerDeliveryId:
          type: string
          nullable: true

    SetStatusInput:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [pending, confirmed, preparing, ready, out_for_delivery, delivered, canceled, problem]

    AssignDelivererInput:
      type: object
      properties:
        delivererId:
          type: string
          nullable: true
