openapi: 3.0.3
info:
  title: DFCP Orders API
  version: "1.0.0"
  description: |
    Orders endpoints (customer + staff). All routes under `/api/orders` are authenticated.
    Notes:
      - `POST /` returns `{ data: { order, orderQR } }`.
      - `GET /my` returns `{ data: Order[] }`.
      - `GET /summary` returns `{ data: OrdersSummaryEnvelope }`.
      - `GET /by-shift` returns `{ data: OrdersForShiftEnvelope }`.
      - For now, the logistics center (LC) is fixed server-side (see controller); `summary` and `by-shift`
        do **not** accept an `lc` query param in this implementation.

servers:
  - url: https://api.example.com/api/orders

tags:
  - name: Orders
    description: Create and query orders

paths:
  /:
    post:
      tags: [Orders]
      summary: Create a new order for the authenticated customer
      description: |
        Creates an order and reserves AMS inventory atomically (FO-centric adjusters).
        - Uses AMS (by `amsId`) as the source of truth for price per KG and shift.
        - On success, also mints/reuses a short-lived order token (QR).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderInput'
            examples:
              mixedExample:
                summary: Mixed kg + units item
                value:
                  amsId: "6715e9e0a1b2c3d4e5f60789"
                  logisticsCenterId: "66e007000000000000000001"
                  deliveryDate: "2025-10-22T09:00:00.000Z"
                  deliveryAddress:
                    street: "123 Main St"
                    city: "Karmiel"
                    country: "IL"
                    zip: "2010000"
                  tolerancePct: 0.1
                  items:
                    - itemId: "68960284330bf1699eee8955"
                      farmerOrderId: "6715ea10a1b2c3d4e5f60790"
                      name: "Lettuce Romaine"
                      category: "Vegetables"
                      imageUrl: "https://cdn.example.com/items/lettuce.jpg"
                      unitMode: "mixed"
                      quantityKg: 1.2
                      units: 2
                      estimatesSnapshot:
                        avgWeightPerUnitKg: 0.45
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      order:
                        $ref: '#/components/schemas/Order'
                      orderQR:
                        $ref: '#/components/schemas/OrderQR'
        '400':
          description: Bad request (validation or AMS/FO mismatch)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWithDetails'
              examples:
                zod:
                  summary: Zod validation error
                  value:
                    error: "ValidationError"
                    details:
                      - path: ["items", 0, "itemId"]
                        message: "Required"
                foNotFound:
                  summary: FO not found in AMS
                  value:
                    error: "BadRequest"
                    details:
                      - "AMS line not found for farmerOrderId 6715ea10a1..."
                      - "Ensure AMS has a line whose farmerOrderId matches the requested item."
                unitsPathInvalid:
                  summary: Units path invalid for item
                  value:
                    error: "BadRequest"
                    details:
                      - "This item is not sold by unit or missing avgWeightPerUnitKg"
        '404':
          description: Not found (AMS doc or FO match failure)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWithDetails'
              examples:
                amsNotFound:
                  value:
                    error: "NotFound"
                    details: ["AvailableMarketStock not found"]
                docOrMatch:
                  value:
                    error: "NotFound"
                    details: ["AvailableMarketStock not found or FO not matched"]
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /my:
    get:
      tags: [Orders]
      summary: Get latest orders for the authenticated customer
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 15
            default: 15
          description: Max number of orders to return (capped at 15).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
        '500':
          description: Server error

  /summary:
    get:
      tags: [Orders]
      summary: Orders summary for current + next shifts (admin/csManager)
      description: |
        Summarizes orders per shift for the **fixed** logistics center configured server-side.
        - Includes the current shift (if any) and the next N shifts.
        - Each entry reports total count and count of `problem` orders.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: count
          schema:
            type: integer
            minimum: 1
            maximum: 10
            default: 5
          description: Number of **next** shifts to include (current shift is added automatically if active).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/OrdersSummaryEnvelope'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (requires role admin or csManager)
        '500':
          description: Server error

  /by-shift:
    get:
      tags: [Orders]
      summary: List orders for a specific date + shift (admin/csManager)
      description: |
        Lists orders for the **fixed** logistics center configured server-side, filtered by `date` and `shift`.
        Optional `status` and projection via `fields`.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date in LC timezone (YYYY-MM-DD).
        - in: query
          name: shift
          required: false
          schema:
            $ref: '#/components/schemas/ShiftName'
          description: Preferred query key for shift name (one of morning|afternoon|evening|night).
        - in: query
          name: shiftName
          required: false
          schema:
            $ref: '#/components/schemas/ShiftName'
          description: Alternative query key accepted by the controller.
        - in: query
          name: status
          schema:
            $ref: '#/components/schemas/OrderStatus'
          description: Optional status filter.
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 200
            default: 50
        - in: query
          name: fields
          schema:
            type: string
          description: >
            Optional comma-separated projection (e.g. `fields=_id,status,customerId,totalPrice`).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/OrdersForShiftEnvelope'
        '400':
          description: Bad request (missing/invalid query)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (requires role admin or csManager)
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # --------------------- Core enums ---------------------
    OrderStatus:
      type: string
      enum: [pending, confirmed, farmer, in-transit, packing, ready_for_pickUp, out_for_delivery, delivered, received, canceled, problem]
    UnitMode:
      type: string
      enum: [kg, unit, mixed]
    ShiftName:
      type: string
      enum: [morning, afternoon, evening, night]

    # --------------------- Shared ---------------------
    Address:
      type: object
      required: [street, city, country]
      properties:
        street: { type: string }
        city: { type: string }
        state: { type: string }
        country: { type: string }
        zip: { type: string }
        note: { type: string }
    AuditEntry:
      type: object
      properties:
        userId:
          type: string
          description: ObjectId
        action:
          type: string
        note:
          type: string
        meta:
          type: object
          additionalProperties: true
        timestamp:
          type: string
          format: date-time

    # --------------------- Create payload ---------------------
    CreateOrderItemInput:
      type: object
      required: [itemId, farmerOrderId, name, unitMode]
      properties:
        itemId:
          type: string
          description: ObjectId of Item
        farmerOrderId:
          type: string
          description: ObjectId of FarmerOrder (FO-centric reservation)
        name:
          type: string
        imageUrl:
          type: string
        category:
          type: string
        # Payload may provide pricePerKg but AMS snapshot is authoritative if present
        pricePerKg:
          type: number
          minimum: 0
          description: Optional; AMS price per KG will override if present.
        unitMode:
          $ref: '#/components/schemas/UnitMode'
        quantityKg:
          type: number
          minimum: 0
          default: 0
        units:
          type: integer
          minimum: 0
          default: 0
        estimatesSnapshot:
          type: object
          properties:
            avgWeightPerUnitKg:
              type: number
              minimum: 0
            stdDevKg:
              type: number
              minimum: 0
        sourceFarmerName:
          type: string
        sourceFarmName:
          type: string
    CreateOrderInput:
      type: object
      required:
        - amsId
        - logisticsCenterId
        - deliveryDate
        - deliveryAddress
        - items
      properties:
        amsId:
          type: string
          description: ObjectId of AvailableMarketStock document
        logisticsCenterId:
          type: string
          description: ObjectId of LogisticsCenter
        deliveryDate:
          type: string
          format: date-time
          description: UTC instant; server computes shift from AMS
        deliveryAddress:
          $ref: '#/components/schemas/Address'
        tolerancePct:
          type: number
          minimum: 0
          maximum: 0.5
          default: 0.1
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CreateOrderItemInput'

    # --------------------- Order model snapshot ---------------------
    OrderItem:
      type: object
      required:
        - itemId
        - name
        - pricePerUnit
        - pricePerKg
        - unitMode
        - sourceFarmerName
        - sourceFarmName
        - farmerOrderId
      properties:
        itemId: { type: string, description: ObjectId }
        name: { type: string }
        imageUrl: { type: string, nullable: true }
        category: { type: string, nullable: true }
        pricePerUnit:
          type: number
          description: Price per KG (legacy name)
        pricePerKg:
          type: number
          description: Explicit price per KG snapshot (same as pricePerUnit)
        derivedUnitPrice:
          type: number
          nullable: true
          description: UI helper price per unit, when unit/mixed
        unitMode:
          $ref: '#/components/schemas/UnitMode'
        quantityKg:
          type: number
          minimum: 0
          default: 0
        units:
          type: integer
          minimum: 0
          default: 0
        estimatesSnapshot:
          type: object
          properties:
            avgWeightPerUnitKg: { type: number, nullable: true }
            stdDevKg: { type: number, nullable: true }
        finalWeightKg:
          type: number
          nullable: true
        finalizedAt:
          type: string
          format: date-time
          nullable: true
        finalizedBy:
          type: string
          description: ObjectId
          nullable: true
        sourceFarmerName: { type: string }
        sourceFarmName: { type: string }
        farmerOrderId:
          type: string
          description: ObjectId
    Order:
      type: object
      required:
        - _id
        - customerId
        - deliveryAddress
        - deliveryDate
        - shiftName
        - LogisticsCenterId
        - amsId
        - items
        - itemsSubtotal
        - deliveryFee
        - totalPrice
        - totalOrderWeightKg
        - status
        - createdAt
        - updatedAt
      properties:
        _id: { type: string, description: ObjectId }
        customerId: { type: string, description: ObjectId }
        deliveryAddress: { $ref: '#/components/schemas/Address' }
        deliveryDate: { type: string, format: date-time }
        shiftName: { $ref: '#/components/schemas/ShiftName' }
        LogisticsCenterId: { type: string, description: ObjectId }
        amsId: { type: string, description: ObjectId }
        items:
          type: array
          items: { $ref: '#/components/schemas/OrderItem' }
        itemsSubtotal: { type: number }
        deliveryFee: { type: number }
        totalPrice: { type: number }
        totalOrderWeightKg: { type: number }
        finalItemsSubtotal: { type: number, nullable: true }
        finalTotalPrice: { type: number, nullable: true }
        finalOrderWeightKg: { type: number, nullable: true }
        tolerancePct: { type: number, default: 0.1 }
        status: { $ref: '#/components/schemas/OrderStatus' }
        assignedDelivererId: { type: string, nullable: true, description: ObjectId }
        customerDeliveryId: { type: string, nullable: true, description: ObjectId }
        historyAuditTrail:
          type: array
          items: { $ref: '#/components/schemas/AuditEntry' }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }

    # --------------------- Summary + listing envelopes ---------------------
    OrdersSummaryEntry:
      type: object
      properties:
        date:
          type: string
          description: yyyy-LL-dd in LC timezone
        shiftName:
          $ref: '#/components/schemas/ShiftName'
        count:
          type: integer
        problemCount:
          type: integer
    OrdersSummaryEnvelope:
      type: object
      properties:
        current:
          allOf:
            - $ref: '#/components/schemas/OrdersSummaryEntry'
          nullable: true
        next:
          type: array
          items:
            $ref: '#/components/schemas/OrdersSummaryEntry'
        tz:
          type: string
          description: LC timezone
        lc:
          type: string
          description: Logistics center id (fixed server-side in this implementation)

    PaginationMeta:
      type: object
      properties:
        lc: { type: string }
        date: { type: string, description: yyyy-LL-dd }
        shiftName: { $ref: '#/components/schemas/ShiftName' }
        tz: { type: string }
        page: { type: integer }
        limit: { type: integer }
        total: { type: integer }
        problemCount: { type: integer }
        pages: { type: integer }
    OrdersForShiftEnvelope:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Order'

    # --------------------- Order token ---------------------
    OrderQR:
      type: object
      properties:
        token: { type: string }
        sig: { type: string }
        scope: { type: string }

    # --------------------- Errors ---------------------
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error code or short message
    ErrorWithDetails:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          properties:
            details:
              type: array
              items:
                oneOf:
                  - type: string
                  - type: object
                    additionalProperties: true
