openapi: 3.0.3
info:
  title: Picker APIs
  version: "1.0.0"

tags:
  - name: Picker
    description: Picker profile, core data & gamification (require authentication)

paths:
  /api/v1/picker/me:
    get:
      tags: [Picker]
      summary: Get my picker profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Picker profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickerProfile"
              example:
                userId: "66f2aa00000000000000002b"
                nickname: "UpdatedPicker"
                status: "active"
                level: 4
                xp: 950
                user:
                  name: "Avi Mizrahi"
                  email: "picker@gmail.com"
                  phone: null
                  role: "picker"
                  logisticCenter:
                    id: "66e007000000000000000001"
                    name: "Zarzir Logistics Center"
                    locationName: "Zarzir"
                  mdCoins: 0
                  activeStatus: true
                currentMonthSchedule: []
                nextMonthSchedule: []
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
    patch:
      tags: [Picker]
      summary: Update my logistic center
      description: >
        Upsert core picker data.  
        - Picker document is created if missing.  
        - `logisticCenterId` is applied to the **User** document (not Picker).  
        - Response **does not** expose a raw `logisticCenterId`; instead it appears as `user.logisticCenter`.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchMeRequest"
            examples:
              changeCenter:
                value: { logisticCenterId: "66e007000000000000000001" }
      responses:
        "200":
          description: Updated picker profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickerProfile"
        "400":
          description: Validation error (e.g., center not found)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden

  /api/v1/picker/me/gamification:
    patch:
      tags: [Picker]
      summary: Update my gamification
      description: >
        Set absolute XP via `xp` **or** add delta via `addXp`.  
        If both are provided, `xp` takes precedence (per controller).
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchGamificationRequest"
            examples:
              setXp:
                value: { xp: 950 }
              addXp:
                value: { addXp: 50 }
      responses:
        "200":
          description: Updated picker profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickerProfile"
        "400":
          description: Bad request (picker not found, invalid numbers, etc.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden

  /api/v1/picker/top:
    get:
      tags: [Picker]
      summary: Get top pickers by completed orders
      description: >
        Returns the top N pickers ordered by **completed orders count** for a given time window.  
        Time window can be either the **current shift today** (`mode=todayShift`) or a **specific month** (`mode=month`).  
        Optionally scoped to a specific logistics center.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: mode
          schema:
            type: string
            enum: [todayShift, month]
            default: todayShift
          description: >
            Ranking mode.  
            - `todayShift` — current active shift today (based on shiftConfig).  
            - `month` — calendar month (uses `month` and `year` if provided).
        - in: query
          name: logisticCenterId
          schema:
            type: string
          required: false
          description: >
            Optional logistics center to scope the ranking to (Mongo ObjectId as string).
        - in: query
          name: month
          schema:
            type: integer
            minimum: 1
            maximum: 12
          required: false
          description: >
            Target month (1-12).  
            Only used when `mode=month`.  
            Defaults to current month if omitted.
        - in: query
          name: year
          schema:
            type: integer
          required: false
          description: >
            Target year (e.g. 2025).  
            Only used when `mode=month`.  
            Defaults to current year if omitted.
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            default: 5
          required: false
          description: >
            Maximum number of pickers to return.  
            Defaults to 5.
      responses:
        "200":
          description: Top pickers ordered by completed orders (descending)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TopPicker"
              example:
                - pickerUserId: "66f2aa00000000000000002b"
                  completedOrders: 42
                  nickname: "SpeedyPicker"
                  status: "active"
                  level: 5
                  xp: 1230
                  user:
                    name: "Avi Mizrahi"
                    email: "picker@gmail.com"
                    phone: null
                    role: "picker"
                    logisticCenterId: "66e007000000000000000001"
                    mdCoins: 0
                    activeStatus: true
                - pickerUserId: "66f2aa000000000000000030"
                  completedOrders: 37
                  nickname: "BoxMaster"
                  status: "active"
                  level: 4
                  xp: 980
                  user:
                    name: "Dana Cohen"
                    email: "picker2@gmail.com"
                    phone: null
                    role: "picker"
                    logisticCenterId: "66e007000000000000000001"
                    mdCoins: 10
                    activeStatus: true
        "400":
          description: Bad request (e.g. invalid month/year)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PickerStatus:
      type: string
      enum: [active, suspended, unactive]

    LogisticCenter:
      type: object
      nullable: true
      properties:
        id:
          type: string
          description: Mongo ObjectId as string
          nullable: true
          example: "66e007000000000000000001"
        name:
          type: string
          nullable: true
          example: "Zarzir Logistics Center"
        locationName:
          type: string
          nullable: true
          example: "Zarzir"

    UserInProfile:
      type: object
      required: [name, email, role, mdCoins, activeStatus]
      properties:
        name:
          type: string
          example: "Avi Mizrahi"
        email:
          type: string
          format: email
          example: "picker@gmail.com"
        phone:
          type: string
          nullable: true
          example: null
        role:
          type: string
          description: One of your defined roles
          example: picker
        logisticCenter:
          $ref: "#/components/schemas/LogisticCenter"
        mdCoins:
          type: number
          example: 0
        activeStatus:
          type: boolean
          example: true

    PickerProfile:
      type: object
      required:
        - userId
        - nickname
        - status
        - level
        - xp
        - user
        - currentMonthSchedule
        - nextMonthSchedule
      properties:
        userId:
          type: string
          description: Picker.userId as string
          example: "66f2aa00000000000000002b"
        nickname:
          type: string
          example: "UpdatedPicker"
        status:
          $ref: "#/components/schemas/PickerStatus"
        level:
          type: integer
          minimum: 1
          example: 4
        xp:
          type: integer
          minimum: 0
          example: 950
        user:
          $ref: "#/components/schemas/UserInProfile"
        currentMonthSchedule:
          type: array
          description: Reserved for future use (currently empty)
          items: {}
        nextMonthSchedule:
          type: array
          description: Reserved for future use (currently empty)
          items: {}

    PatchMeRequest:
      type: object
      additionalProperties: false
      properties:
        logisticCenterId:
          type: string
          description: >
            Logistic center to assign to the user (ObjectId as string).  
            **Note:** This field is **input only**; responses never include any raw `logisticCenterId`.
          example: "66e007000000000000000001"
      required: [logisticCenterId]

    PatchGamificationRequest:
      type: object
      additionalProperties: false
      properties:
        xp:
          type: integer
          minimum: 0
          description: Set absolute XP value
          example: 950
        addXp:
          type: integer
          description: Additive XP delta (can be negative; service clamps total at 0)
          example: 50
      minProperties: 1

    TopPickerUserSummary:
      type: object
      description: Lightweight user info inside a top-pickers ranking entry.
      properties:
        name:
          type: string
          example: "Avi Mizrahi"
        email:
          type: string
          format: email
          example: "picker@gmail.com"
        phone:
          type: string
          nullable: true
          example: null
        role:
          type: string
          example: "picker"
        logisticCenterId:
          type: string
          description: Raw ObjectId of the user's logistics center (if any).
          nullable: true
          example: "66e007000000000000000001"
        mdCoins:
          type: number
          example: 0
        activeStatus:
          type: boolean
          example: true

    TopPicker:
      type: object
      description: Ranking entry for a picker, ordered by completed orders.
      properties:
        pickerUserId:
          type: string
          description: User _id of the picker (as string)
          example: "66f2aa00000000000000002b"
        completedOrders:
          type: integer
          description: Number of completed orders in the selected time window
          example: 42
        nickname:
          type: string
          nullable: true
          example: "SpeedyPicker"
        status:
          $ref: "#/components/schemas/PickerStatus"
        level:
          type: integer
          minimum: 1
          example: 5
        xp:
          type: integer
          minimum: 0
          example: 1230
        user:
          $ref: "#/components/schemas/TopPickerUserSummary"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Picker not found. Create picker first."
