openapi: 3.0.3
info:
  title: User (Customer) API
  version: 1.0.0
  description: Endpoints for customer self-service (addresses, name, contact info)

servers:
  - url: /api/v1

tags:
  - name: User
    description: Customer self-service routes (require authentication)

paths:
  /user/addresses:
    get:
      tags: [User]
      summary: Get my addresses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of addresses for the authenticated user
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Address'
              example:
                data:
                  - lnt: 35.503
                    alt: 33.02
                    address: "Kiryat Shmona, Israel"
                    logisticCenterId: "66e007000000000000000001"
        '401':
          description: Unauthorized

    post:
      tags: [User]
      summary: Add a new address (pins LC to default for now)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAddressInput'
            example:
              lnt: 35.503
              alt: 33.02
              address: "Kiryat Shmona, Israel"
      responses:
        '201':
          description: Updated list of addresses (with default LC assigned)
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Address'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /user/name:
    get:
      tags: [User]
      summary: Get my name
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User name
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                        example: "Levy Cohen"
        '401':
          description: Unauthorized

  /user/contact:
    get:
      tags: [User]
      summary: Get my contact info
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Contact info for the authenticated user
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/ContactInfo'
              example:
                data:
                  name: "Levy Cohen"
                  email: "levy.cohen@example.com"
                  phone: "+972-52-123-4567"
                  birthday: "1992-05-14"
        '401':
          description: Unauthorized

    patch:
      tags: [User]
      summary: Update my email or phone
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContactInput'
            examples:
              updateEmail:
                value: { email: "new.email@example.com" }
              updatePhone:
                value: { phone: "+972-52-765-4321" }
              both:
                value: { email: "new.email@example.com", phone: "+972-52-765-4321" }
      responses:
        '200':
          description: Updated contact info
          content:
            application/json:
              schema:
                type: object
                required: [data]
                properties:
                  data:
                    $ref: '#/components/schemas/ContactInfo'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '409':
          description: Email already in use

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Address:
      type: object
      required: [lnt, alt, address, logisticCenterId]
      properties:
        lnt:
          type: number
          description: Longitude (kept as `lnt` per schema)
          example: 35.503
        alt:
          type: number
          description: Latitude (kept as `alt` per schema)
          example: 33.02
        address:
          type: string
          example: "Kiryat Shmona, Israel"
        logisticCenterId:
          type: string
          description: Temporarily pinned to default LC id by the service
          example: "66e007000000000000000001"

    NewAddressInput:
      type: object
      required: [lnt, alt, address]
      properties:
        lnt: { type: number, example: 35.503 }
        alt: { type: number, example: 33.02 }
        address: { type: string, example: "Kiryat Shmona, Israel" }

    ContactInfo:
      type: object
      required: [name, email]
      properties:
        name: { type: string, example: "Levy Cohen" }
        email: { type: string, format: email, example: "levy.cohen@example.com" }
        phone: { type: string, nullable: true, example: "+972-52-123-4567" }
        birthday: { type: string, format: date, nullable: true, example: "1992-05-14" }

    UpdateContactInput:
      type: object
      description: Supply at least one of the fields
      properties:
        email: { type: string, format: email, example: "new.email@example.com" }
        phone: { type: string, example: "+972-52-765-4321" }
